language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - windows

jobs:
  include:
    - stage: coverage
      os: linux
      rust: nightly

      before_script:
        - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

      script:
        - rustup component add llvm-tools-preview
        - export RUSTFLAGS="-Zinstrument-coverage"
        - cargo build --verbose
        - LLVM_PROFILE_FILE="your_name-%p-%m.profraw" cargo test --verbose
        - ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
        - bash <(curl -s https://codecov.io/bash) -f lcov.info
